# Generated by Django 3.2.15 on 2022-08-19 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_name', models.CharField(max_length=50)),
                ('do_spe', models.CharField(max_length=250)),
                ('do_img', models.ImageField(upload_to='doctors')),
                ('do_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.departmets')),
            ],
        ),
    ]
